name: yolo12n
task: detect
pretrained: true
weights: yolo12n.pt

num_classes: 1
class_names:
  - "tooth"

inference:
  conf_threshold: 0.25
  iou_threshold:  0.45
  max_det:        50
  img_size:       1024
  device:         auto
